### ISSUE TITLE
provider: support eth_sign and personal_sign

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#204] opened 2021-08-09 14:31 UTC
Some dapps like opensea/rarible need to sign a message with the user's wallet to function properly. Also, some of them already support EIP-1271 but there's no convenient way for them to sign a message if they use safe-apps-provider

**Comment by ennisjo** [comment] 2021-08-09 15:30
Worth trying out on https://snapshot.org/#/ also, when added.

**Comment by bonustrack** [comment] 2021-08-09 15:55
At Snapshot we are using `personal_sign` here is how signing is done currently:
https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils/web3.ts#L5
You can test it here, you can cast a vote with any wallet on this proposal: https://snapshot.org/#/fabien.eth/proposal/QmUQ3ytu3JQdbVScFVkEsPtPHc6REEKCtYb7wTcaKkukrR

As @ennisjo said we are moving to typedData (EIP712) to sign message this is how we do it:
https://github.com/snapshot-labs/snapshot.js/blob/master/src/sign/index.ts#L42
This is something you can test by voting here: 
https://demo.snapshot.org/#/fabien.eth/proposal/QmXRTUuYMu7zsP7ULFKYvhh9W8Rq96LKPzFrfc5ih2zZue 

In the latest version of typedData (v4) it's possible to use array types, I don't think it require change on the contract to support it, it may not work with WalletConnect related issue https://github.com/WalletConnect/walletconnect-monorepo/issues/546 but if you want to test array type you can vote here:
https://demo.snapshot.org/#/fabien.eth/proposal/QmSWbDMWZMWEBppvWhKSy4zhyLDsXeoKyKC5fSL5UcmvM8

**Comment by mikheevm** [comment] 2021-08-10 14:00
@bonustrack will you drop support for eth_sign and personal_sign?

**Comment by bonustrack** [comment] 2021-08-10 14:25
@mikheevm We will support both `personal_sign` and `typedData` for ~2 months but then drop support for `personal_sign`.

**Comment by mikheevm** [comment] 2021-08-10 15:03
Because of changes in singing in 1.3.0, the current plan is:
1. Support eth_sign/personal_sign/eth_signTypedData for 1.1.1 contracts, both in SDK/WC app
2. When SignMessage library is deployed/audited (it's required for signing on 1.3.0), introduce signing support for 1.3.0
3. Make 1.1.1 contracts use SignMessage library too
cc @rmeissner

**Comment by yelouafi** [comment] 2021-08-31 22:13
Will this work also for apps that are connecting indirectly via a wallet like `walletConnect`?

Our use case is basically like general web apps such as opensea. The webapp allows users to connect through many wallet choices, and we use `personal_sign` to verify users after the connections is established. Some users tried to connect to gnosis via walletConnect  but fail when signing with a `METHOD_NOT_SUPPORTED` error (we use the walletConnect web3 provider).

**Comment by mikheevm** [comment] 2021-09-01 08:05
@yelouafi yep, this is the plan. The app needs to support EIP-1271.

**Comment by mikheevm** [comment] 2021-09-20 13:26
> is there a timeline on this feature? I am running into a wall with a similar Gnosis Safe x WalletConect => OpenSea setup myself. or can you think of an alternative multisig setup?

The feature will go live this week, but the problem with OpenSea is not going to be fixed because OpenSea doesn't support smart contract signatures. We're chasing them in that regard.

**Comment by tech4242** [comment] 2021-09-20 13:54
thank you for the quick reply @mikheevm! based on XP is this something we can "expect" soon or will it be a long process (thinking of looking for alternatives if that's the case)

**Comment by mikheevm** [comment] 2021-09-20 14:13
> thank you for the quick reply @mikheevm! based on XP is this something we can "expect" soon or will it be a long process (thinking of looking for alternatives if that's the case)

They're being chased for quite a long time by us and the Argent wallet team. They're dealing with exponential growth and their focus is entirely on that. I'd say this is not something to expect soon

**Comment by tech4242** [comment] 2021-09-20 14:15
thank you for the honest feedback! 🙏

**Closed** 2021-09-27 09:35 UTC

**Comment by midgerate** [comment] 2022-05-15 01:48
Hey @mikhailxyz does gnosis safe support EIP712 typed array now? I see that this issue was closed.

**Comment by mikhailxyz** [comment] 2022-05-16 08:40
> Hey @mikhailxyz does gnosis safe support EIP712 typed array now? I see that this issue was closed.

nop it doesn't yet, the issue is only about eth_sign and personal_sign

**Comment by midgerate** [comment] 2022-05-17 05:27
@mikhailxyz should I create a new issue? is it on roadmap? Can I help develop it? We need this over at snapshot.org

**Comment by mikhailxyz** [comment] 2022-05-17 10:05
> @mikhailxyz should I create a new issue? is it on roadmap? Can I help develop it? We need this over at snapshot.org

it's not on the roadmap atm, you can create a new issue 🙂  contributions are heavily encouraged!
